language: node_js
node_js:
  - "node"
before_script:
  - cd ./ReportJ.Extension.Chrome
  # https://github.com/sass/node-sass/issues/1991#issuecomment-306437979
  - rm -rf node_modules
  - rm package-lock.json
  - npm cache clean
  - npm install
script:
  - npm run build:release
cache:
  directories:
    - "node_modules"